### ISSUE TITLE
APP闪退，基本不能用

### ISSUE THREAD

**Issue by hale2005** [nesror/SmartHouse#1]
Android 12 ，V1.2.0

**Comment by nesror** [comment]
手机什么型号，我找下错误日志。另外旧版本闪退吗？

**Comment by hale2005** [comment]
第一次装，荣耀X20,开启-设置-传感器设置-传感器后台服务，不再重启

从 Windows 版邮件发送

发件人: nestor
发送时间: 2023年4月29日 14:33
收件人: nesror/SmartHouse
抄送: hale2005; Author
主题: Re:_[nesror/SmartHouse]_APP闪退，基本不能用_(Issue_#1)

手机什么型号，我找下错误日志。另外旧版本闪退吗？

**Comment by nesror** [comment]
> 第一次装，荣耀X20,开启-设置-传感器设置-传感器后台服务，不再重启 从 Windows 版邮件发送 发件人: nestor 发送时间: 2023年4月29日 14:33 收件人: nesror/SmartHouse 抄送: hale2005; Author 主题: Re:_[nesror/SmartHouse]_APP闪退，基本不能用_(Issue_#1) 手机什么型号，我找下错误日志。另外旧版本闪退吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

firebase上没找到这个机型的错误日志。。51节后会发个修复firebase上所有出现的bug的包，到时候可以再试试

**Comment by nesror** [comment]
使用1.2.5或1.3.0试试
