### ISSUE TITLE
能否新增隐藏首页语音图标，底部tab等功能呢

### ISSUE THREAD

**Issue by zhangziran** [nesror/SmartHouse#11]
因为从语音来说，接入系统自带的小爱或其他更快捷一些。

至于底部tab，一般家里可能分得不是那么清楚

**Comment by nesror** [comment]
后续增加个首页全屏功能，开启就关闭语音入口的tab

**Comment by zhangziran** [comment]
哈哈，首页全屏这样确实是便利很多

**Comment by nesror** [comment]
https://github.com/nesror/SmartHouse/releases/tag/v3.0.0-rc
app设置-沉浸模式

**Comment by zhangziran** [comment]
> https://github.com/nesror/SmartHouse/releases/tag/v3.0.0-rc app设置-沉浸模式

😂这么快，但是我下载测试了下打开这个模式保存不了。重启就会显示为关闭。miui14，安卓13

**Comment by nesror** [comment]
> > https://github.com/nesror/SmartHouse/releases/tag/v3.0.0-rc app设置-沉浸模式
> 
> 😂这么快，但是我下载测试了下打开这个模式保存不了。重启就会显示为关闭。miui14，安卓13

bug，等今天晚上和其他问题一起修复的版本

**Comment by zhangziran** [comment]
> > > https://github.com/nesror/SmartHouse/releases/tag/v3.0.0-rc app设置-沉浸模式
> > 
> > 
> > 😂这么快，但是我下载测试了下打开这个模式保存不了。重启就会显示为关闭。miui14，安卓13
> 
> bug，等今天晚上和其他问题一起修复的版本

google play版本app设置中的tab配置信息，测试版没了啊。导致配置信息没法手动复制过来，同步的话也得同签名app才能同步啊。

**Comment by nesror** [comment]
> > > > https://github.com/nesror/SmartHouse/releases/tag/v3.0.0-rc app设置-沉浸模式
> > > 
> > > 
> > > 😂这么快，但是我下载测试了下打开这个模式保存不了。重启就会显示为关闭。miui14，安卓13
> > 
> > 
> > bug，等今天晚上和其他问题一起修复的版本
> 
> google play版本app设置中的tab配置信息，测试版没了啊。导致配置信息没法手动复制过来，同步的话也得同签名app才能同步啊。

还有这种操作。。页面选项太多把他当冗余功能注释掉了。。先可以用使用其他设备tab配置功能试试，填需要同步的设备名称

**Comment by SingcoLee** [comment]
您好，您的邮件我已收到，看到后我会尽快回复。祝您工作生活愉快！
