### ISSUE TITLE
一直在加载转圈圈是为啥，卸载重装也一样

### ISSUE THREAD

**Issue by conscloud** [nesror/SmartHouse#12]

**Comment by nesror** [comment]
多久，首次设备多的话要稍等下。可以查看下ha页面设备越服务的移动应用力有没有你的手机。如果没有就是没登录成功。

**Comment by conscloud** [comment]
> 多久，首次设备多的话要稍等下。可以查看下ha页面设备越服务的移动应用力有没有你的手机。如果没有就是没登录成功。

重启下HA可以了
