### ISSUE TITLE
大佬能否做个超精简版本

### ISSUE THREAD

**Issue by gky008** [nesror/SmartHouse#13]
就是只需要输入令牌就能登陆(老手机由于webview版本过低不能显示用户名密码登陆)，不提供任何功能，只是把手机的传感器可以有选择的推送到ha？这样可以废物利用把换盆的旧手机当传感器用。

**Comment by SingcoLee** [comment]
您好，您的邮件我已收到，看到后我会尽快回复。祝您工作生活愉快！

**Comment by nesror** [comment]
> 就是只需要输入令牌就能登陆(老手机由于webview版本过低不能显示用户名密码登陆)，不提供任何功能，只是把手机的传感器可以有选择的推送到ha？这样可以废物利用把换盆的旧手机当传感器用。

可以，国庆后安排

**Comment by nesror** [comment]
> 就是只需要输入令牌就能登陆(老手机由于webview版本过低不能显示用户名密码登陆)，不提供任何功能，只是把手机的传感器可以有选择的推送到ha？这样可以废物利用把换盆的旧手机当传感器用。

https://github.com/nesror/SmartHouse/releases/tag/v3.2.2

下载mini版本
