### ISSUE TITLE
空调温度无法调节，3.3.1版本

### ISSUE THREAD

**Issue by zhangziran** [nesror/SmartHouse#16]
空调温度无法调节，3.3.1版本

**Comment by nesror** [comment]
带我验证下
之前的版本可以控制吗

**Comment by zhangziran** [comment]
> 带我回家后验证下 之前的版本可以控制吗

之前的版本空调支持还不全面，现在是温度反馈可以、温度控制不行，其余的调整风速、模式都是可以的。

**Comment by nesror** [comment]
> > 带我回家后验证下 之前的版本可以控制吗
> 
> 之前的版本空调支持还不全面，现在是温度反馈可以、温度控制不行，其余的调整风速、模式都是可以的。

测试了下，米家空调伴侣，小米空调，美的空调都能控制。你的ha版本和空调型号，还有空调接入方式是什么？

**Comment by zhangziran** [comment]
> > > 带我回家后验证下 之前的版本可以控制吗
> > 
> > 
> > 之前的版本空调支持还不全面，现在是温度反馈可以、温度控制不行，其余的调整风速、模式都是可以的。
> 
> 测试了下，米家空调伴侣，小米空调，美的空调都能控制。你的ha版本和空调型号，还有空调接入方式是什么？

空调型号
使用x12（mqtt）接入ha，通过ha的climate.x12_aircon组件可以正常控制

ha版本
Home Assistant

Core
2024.8.3
Supervisor
2024.10.2
Operating System
13.1
Frontend
20240809.0

**Comment by nesror** [comment]
> > > > 带我回家后验证下 之前的版本可以控制吗
> > > 
> > > 
> > > 之前的版本空调支持还不全面，现在是温度反馈可以、温度控制不行，其余的调整风速、模式都是可以的。
> > 
> > 
> > 测试了下，米家空调伴侣，小米空调，美的空调都能控制。你的ha版本和空调型号，还有空调接入方式是什么？
> 
> 空调型号 使用x12（mqtt）接入ha，通过ha的climate.x12_aircon组件可以正常控制
> 
> ha版本 Home Assistant
> 
> Core 2024.8.3 Supervisor 2024.10.2 Operating System 13.1 Frontend 20240809.0

可以附带该设备的完整状态属性吗，如下图
![image](https://github.com/user-attachments/assets/de00d2c4-9781-40b8-b47d-ca5dcd2fa17c)

**Comment by nesror** [comment]
> * current_temperature



> > > > > > 带我回家后验证下 之前的版本可以控制吗
> > > > > 
> > > > > 
> > > > > 之前的版本空调支持还不全面，现在是温度反馈可以、温度控制不行，其余的调整风速、模式都是可以的。
> > > > 
> > > > 
> > > > 测试了下，米家空调伴侣，小米空调，美的空调都能控制。你的ha版本和空调型号，还有空调接入方式是什么？
> > > 
> > > 
> > > 空调型号 使用x12（mqtt）接入ha，通过ha的climate.x12_aircon组件可以正常控制
> > > ha版本 Home Assistant
> > > Core 2024.8.3 Supervisor 2024.10.2 Operating System 13.1 Frontend 20240809.0
> > 
> > 
> > 可以附带该设备的完整状态属性吗，如下图 ![image](https://private-user-images.githubusercontent.com/8413360/378184140-de00d2c4-9781-40b8-b47d-ca5dcd2fa17c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzAyNDAsIm5iZiI6MTcyOTQyOTk0MCwicGF0aCI6Ii84NDEzMzYwLzM3ODE4NDE0MC1kZTAwZDJjNC05NzgxLTQwYjgtYjQ3ZC1jYTVkY2QyZmExN2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMTMxMjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmEzOTI4MmU2NzA3OWI0ZmZlOGI0ODU4NWYxNjgyZTBjZmE0MmE2NTFlZWQ0MjMzNjQwOTE4ZTc4NTU5OGI4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2h_g1OWgtYpoafUUi6VgRcP1nuvrkkFjslIboig76q4)
> 
> `hvac_modes:
> 
> * "off"
> * auto
> * cool
> * heat
> * dry
> * fan_only
>   min_temp: 16
>   max_temp: 30
>   target_temp_step: 1
>   fan_modes:
> * Auto
> * Min
> * Low
> * Medium
> * High
> * Max
>   swing_modes:
> * "Off"
> * Auto
> * Highest
> * High
> * Middle
> * Low
> * Lowest
>   current_temperature: null
>   temperature: 17
>   fan_mode: Max
>   swing_mode: "Off"
>   friendly_name: 卧室空调
>   supported_features: 425
>   `

原因找到了，你的current_temperature为null。下版本处理

**Comment by nesror** [comment]
> > > > > > 带我回家后验证下 之前的版本可以控制吗
> > > > > 
> > > > > 
> > > > > 之前的版本空调支持还不全面，现在是温度反馈可以、温度控制不行，其余的调整风速、模式都是可以的。
> > > > 
> > > > 
> > > > 测试了下，米家空调伴侣，小米空调，美的空调都能控制。你的ha版本和空调型号，还有空调接入方式是什么？
> > > 
> > > 
> > > 空调型号 使用x12（mqtt）接入ha，通过ha的climate.x12_aircon组件可以正常控制
> > > ha版本 Home Assistant
> > > Core 2024.8.3 Supervisor 2024.10.2 Operating System 13.1 Frontend 20240809.0
> > 
> > 
> > 可以附带该设备的完整状态属性吗，如下图 ![image](https://private-user-images.githubusercontent.com/8413360/378184140-de00d2c4-9781-40b8-b47d-ca5dcd2fa17c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzAyNDAsIm5iZiI6MTcyOTQyOTk0MCwicGF0aCI6Ii84NDEzMzYwLzM3ODE4NDE0MC1kZTAwZDJjNC05NzgxLTQwYjgtYjQ3ZC1jYTVkY2QyZmExN2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMTMxMjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmEzOTI4MmU2NzA3OWI0ZmZlOGI0ODU4NWYxNjgyZTBjZmE0MmE2NTFlZWQ0MjMzNjQwOTE4ZTc4NTU5OGI4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2h_g1OWgtYpoafUUi6VgRcP1nuvrkkFjslIboig76q4)
> 
> `hvac_modes:
> 
> * "off"
> * auto
> * cool
> * heat
> * dry
> * fan_only
>   min_temp: 16
>   max_temp: 30
>   target_temp_step: 1
>   fan_modes:
> * Auto
> * Min
> * Low
> * Medium
> * High
> * Max
>   swing_modes:
> * "Off"
> * Auto
> * Highest
> * High
> * Middle
> * Low
> * Lowest
>   current_temperature: null
>   temperature: 17
>   fan_mode: Max
>   swing_mode: "Off"
>   friendly_name: 卧室空调
>   supported_features: 425
>   `

看这个应该是没问题的，等我找个mtqq接入的空调伴侣之类的试试

**Comment by zhangziran** [comment]
> > > > > > > 带我回家后验证下 之前的版本可以控制吗
> > > > > > 
> > > > > > 
> > > > > > 之前的版本空调支持还不全面，现在是温度反馈可以、温度控制不行，其余的调整风速、模式都是可以的。
> > > > > 
> > > > > 
> > > > > 测试了下，米家空调伴侣，小米空调，美的空调都能控制。你的ha版本和空调型号，还有空调接入方式是什么？
> > > > 
> > > > 
> > > > 空调型号 使用x12（mqtt）接入ha，通过ha的climate.x12_aircon组件可以正常控制
> > > > ha版本 Home Assistant
> > > > Core 2024.8.3 Supervisor 2024.10.2 Operating System 13.1 Frontend 20240809.0
> > > 
> > > 
> > > 可以附带该设备的完整状态属性吗，如下图 ![image](https://private-user-images.githubusercontent.com/8413360/378184140-de00d2c4-9781-40b8-b47d-ca5dcd2fa17c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzAyNDAsIm5iZiI6MTcyOTQyOTk0MCwicGF0aCI6Ii84NDEzMzYwLzM3ODE4NDE0MC1kZTAwZDJjNC05NzgxLTQwYjgtYjQ3ZC1jYTVkY2QyZmExN2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMTMxMjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmEzOTI4MmU2NzA3OWI0ZmZlOGI0ODU4NWYxNjgyZTBjZmE0MmE2NTFlZWQ0MjMzNjQwOTE4ZTc4NTU5OGI4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2h_g1OWgtYpoafUUi6VgRcP1nuvrkkFjslIboig76q4)
> > 
> > 
> > `hvac_modes:
> > 
> > * "off"
> > * auto
> > * cool
> > * heat
> > * dry
> > * fan_only
> >   min_temp: 16
> >   max_temp: 30
> >   target_temp_step: 1
> >   fan_modes:
> > * Auto
> > * Min
> > * Low
> > * Medium
> > * High
> > * Max
> >   swing_modes:
> > * "Off"
> > * Auto
> > * Highest
> > * High
> > * Middle
> > * Low
> > * Lowest
> >   current_temperature: null
> >   temperature: 17
> >   fan_mode: Max
> >   swing_mode: "Off"
> >   friendly_name: 卧室空调
> >   supported_features: 425
> >   `
> 
> 看这个应该是没问题的，等我找个mtqq接入的空调伴侣之类的试试

好的，需要的话发下mqtt服务器，我注册一个设备上去测试。。。

**Comment by nesror** [comment]
试试3.3.4版本

**Comment by SingcoLee** [comment]
您好，您的邮件我已收到，看到后我会尽快回复。祝您工作生活愉快！

**Comment by zhangziran** [comment]
> 试试3.3.4版本


Uploading Screenrecorder-2024-11-07-10-22-28-396.mp4…

**Comment by zhangziran** [comment]
> 试试3.3.4版本

已测试，以下为录屏

https://github.com/user-attachments/assets/bfb09dbc-f374-4cc4-a8a3-881ba4b8c389

**Comment by zhangziran** [comment]
> > 试试3.3.4版本
> 
> 已测试，以下为录屏
> 
>  Screenrecorder-2024-11-07-10-22-28-396.mp4

附上一个国内版录屏地址
https://prod-vod.miyoushe.com/oS4NS8sNFLBMtQFvTOclZdzF4zlDVZ5DdCfVww/Screenrecorder-2024-11-07-10-22-28-396.mp4

**Comment by nesror** [comment]
> > > 试试3.3.4版本
> > 
> > 
> > 已测试，以下为录屏
> > Screenrecorder-2024-11-07-10-22-28-396.mp4
> 
> 附上一个国内版录屏地址 https://prod-vod.miyoushe.com/oS4NS8sNFLBMtQFvTOclZdzF4zlDVZ5DdCfVww/Screenrecorder-2024-11-07-10-22-28-396.mp4

尝试下ha里执行是否有效
![image](https://github.com/user-attachments/assets/8eb3a6a1-4ceb-42de-a930-030794cf9f6a)
`
action: climate.set_temperature
target:
  entity_id: climate.lumi_v3_0d59_air_conditioner
data:
  temperature: 22
`

**Comment by zhangziran** [comment]
> > > > 试试3.3.4版本
> > > 
> > > 
> > > 已测试，以下为录屏
> > > Screenrecorder-2024-11-07-10-22-28-396.mp4
> > 
> > 
> > 附上一个国内版录屏地址 https://prod-vod.miyoushe.com/oS4NS8sNFLBMtQFvTOclZdzF4zlDVZ5DdCfVww/Screenrecorder-2024-11-07-10-22-28-396.mp4
> 
> 尝试下ha里执行是否有效 ![image](https://private-user-images.githubusercontent.com/8413360/383833695-8eb3a6a1-4ceb-42de-a930-030794cf9f6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjA0MDcsIm5iZiI6MTczMDk2MDEwNywicGF0aCI6Ii84NDEzMzYwLzM4MzgzMzY5NS04ZWIzYTZhMS00Y2ViLTQyZGUtYTkzMC0wMzA3OTRjZjlmNmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDdUMDYxNTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRmNzcwOTdiYmQxZjA2MjYwMDA3YWU5NDQxOTU1NzFiZWZhZDM3Njg0YTg5ZWRiNGQwZjQyZTUwYzdkMGU0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Dq7jiiGo35sh9gSuNC_ieIBpBN0qbrCRncZ-lmoY14g)
> 
> ```
> action: climate.set_temperature
> target:
>   entity_id: climate.lumi_v3_0d59_air_conditioner
> data:
>   temperature: 22
> ```
ha本身命令执行控制正常，实时反馈
![image](https://github.com/user-attachments/assets/6ff08e7b-062f-43b2-9888-950bc3e8197a)
![image](https://github.com/user-attachments/assets/2d762983-2ff9-4674-acc9-8627136f2775)

haweb执行控制正常，实时反馈

https://github.com/user-attachments/assets/34172318-42c5-4d0c-a628-2f80aacbe44a

**Comment by nesror** [comment]
> > > > > 试试3.3.4版本
> > > > 
> > > > 
> > > > 已测试，以下为录屏
> > > > Screenrecorder-2024-11-07-10-22-28-396.mp4
> > > 
> > > 
> > > 附上一个国内版录屏地址 https://prod-vod.miyoushe.com/oS4NS8sNFLBMtQFvTOclZdzF4zlDVZ5DdCfVww/Screenrecorder-2024-11-07-10-22-28-396.mp4
> > 
> > 
> > 尝试下ha里执行是否有效 ![image](https://private-user-images.githubusercontent.com/8413360/383833695-8eb3a6a1-4ceb-42de-a930-030794cf9f6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjA0MDcsIm5iZiI6MTczMDk2MDEwNywicGF0aCI6Ii84NDEzMzYwLzM4MzgzMzY5NS04ZWIzYTZhMS00Y2ViLTQyZGUtYTkzMC0wMzA3OTRjZjlmNmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDdUMDYxNTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRmNzcwOTdiYmQxZjA2MjYwMDA3YWU5NDQxOTU1NzFiZWZhZDM3Njg0YTg5ZWRiNGQwZjQyZTUwYzdkMGU0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Dq7jiiGo35sh9gSuNC_ieIBpBN0qbrCRncZ-lmoY14g)
> > ```
> > action: climate.set_temperature
> > target:
> >   entity_id: climate.lumi_v3_0d59_air_conditioner
> > data:
> >   temperature: 22
> > ```
> 
> ha本身命令执行控制正常，实时反馈 ![image](https://private-user-images.githubusercontent.com/1969467/383837603-6ff08e7b-062f-43b2-9888-950bc3e8197a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjI3NDAsIm5iZiI6MTczMDk2MjQ0MCwicGF0aCI6Ii8xOTY5NDY3LzM4MzgzNzYwMy02ZmYwOGU3Yi0wNjJmLTQzYjItOTg4OC05NTBiYzNlODE5N2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDdUMDY1NDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmUxMGU2YTU1ODk0YzM4M2Y4NzA1MzJlMzY0NWFiMGM2MjhjNTZjYmE5ZDIzM2Y3MjNkNjE2NmQyMDI4OGZlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GB3fniesIwCLjkzQuNxwyUbi4Vnx47y9WdZpYURQBtc) ![image](https://private-user-images.githubusercontent.com/1969467/383837688-2d762983-2ff9-4674-acc9-8627136f2775.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjI3NDAsIm5iZiI6MTczMDk2MjQ0MCwicGF0aCI6Ii8xOTY5NDY3LzM4MzgzNzY4OC0yZDc2Mjk4My0yZmY5LTQ2NzQtYWNjOS04NjI3MTM2ZjI3NzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDdUMDY1NDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjU5MTVlN2NmOWI2ZjJmYjhhMTg4NWRkODgwZmRlYzdlMWU5N2M5MDc2ZGM3MGU5MmFhNzM5NzQ5ZjFmYTIzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.X0BgtopGszUwJoxbOmquNHnBcFNqXfblqZSUHWudp1s)
> 
> haweb执行控制正常，实时反馈
> 
>  Screenrecorder-2024-11-07-14-13-33-408_2024117142022.mp4

手机啥型号，我得怀疑兼容性问题的。。。app本身也是通过websocket发送这个命令的

**Comment by nesror** [comment]
试试这个版本（不要解压，去掉.zip），发送命令前会先提示set_temperature的值
[app-github-release.apk.zip](https://github.com/user-attachments/files/17657988/app-github-release.apk.zip)

**Comment by zhangziran** [comment]
> 试试这个版本（不要解压，去掉.zip），发送命令前会先提示set_temperature的值 [app-github-release.apk.zip](https://github.com/user-attachments/files/17657988/app-github-release.apk.zip)

大佬问题解决，能请教下是什么问题吗

https://github.com/user-attachments/assets/f4e9e884-ec39-4ad9-aef9-4ba44982e8bf

**Comment by nesror** [comment]
> > 试试这个版本（不要解压，去掉.zip），发送命令前会先提示set_temperature的值 [app-github-release.apk.zip](https://github.com/user-attachments/files/17657988/app-github-release.apk.zip)
> 
> 大佬问题解决，能请教下是什么问题吗
> 
>  Screenrecorder-2024-11-07-18-11-02-989.mp4

你的temperature有时候不是int类型，现在转成int后再发送
