### ISSUE TITLE
安卓3.4.2版本传感器无法显示之前是正常的

### ISSUE THREAD

**Issue by zhangziran** [nesror/SmartHouse#19]
问题如视频所示

https://github.com/user-attachments/assets/41e6e25c-0a4f-4d15-a02f-23dd36235f9f

**Comment by zhangziran** [comment]
本来传感器是首页直接显示，但新版本传感器却识别成了开关，

**Comment by zhangziran** [comment]
升级github最新的3.4.3问题依然存在，强制
![Screenshot_2024-11-26-00-34-14-140_cn yzapp flutter ha_github](https://github.com/user-attachments/assets/ee287f3b-4b36-4454-8f89-e7835d124383)
降级退回3.3.4正常

**Comment by nesror** [comment]
3.4.4
https://github.com/nesror/SmartHouse/releases/tag/v3.4.4
