### ISSUE TITLE
平板安卓6.0  ID 换绑后 点击赞助 显示未赞助 点击赞助没有反应 

### ISSUE THREAD

**Issue by diy2008** [nesror/SmartHouse#21]
**bug描述**

**版本信息**
1. SmartHouse版本  3.5.0
3. 设备类型（Android，iOS），版本 6.0
2. HomeAssistant版本

**Comment by nesror** [comment]
是换绑后，原先那台手机显示未赞助，点击赞助没有反应。
还是新换的那台显示未赞助

**Comment by diy2008** [comment]
换绑的新设备 显示未赞助 点击赞助没有反应

**Comment by nesror** [comment]
> 换绑的新设备 显示未赞助 点击赞助没有反应

公众号回复我下么我检查下数据库里的设备id

**Comment by nesror** [comment]
新版已经解决，新设备需要手动点击设置-vip-赞助状态。如果不行就重新换绑下
