### ISSUE TITLE
toast 提示 webhook id is empty

### ISSUE THREAD

**Issue by three1bro** [nesror/SmartHouse#5]
toast 提示 webhook id is empty

**Comment by nesror** [comment]
是不是手动删掉了ha设备->移动应用->本机的设备？或者第一次注册设备失败了
点下：app->设置->传感器设置->右上角重新注册 试试

**Comment by SamuelReeves** [comment]
我的也是这样显示的，一开始还以为是非会员会这样显示，后面购买了vip还是这样显示，一脸懵逼。

**Comment by nesror** [comment]
> 我的也是这样显示的，一开始还以为是非会员会这样显示，后面购买了vip还是这样显示，一脸懵逼。

app->设置->传感器设置->右上角重新注册 这样可以解决吗

**Comment by SamuelReeves** [comment]
> > 我的也是这样显示的，一开始还以为是非会员会这样显示，后面购买了vip还是这样显示，一脸懵逼。
> 
> app->设置->传感器设置->右上角重新注册 这样可以解决吗

解决不了的，我把ha里的移动应用项目删了，把app删了，再重新来一遍还是这样显示

**Comment by nesror** [comment]
> > > 我的也是这样显示的，一开始还以为是非会员会这样显示，后面购买了vip还是这样显示，一脸懵逼。
> > 
> > 
> > app->设置->传感器设置->右上角重新注册 这样可以解决吗
> 
> 解决不了的，我把ha里的移动应用项目删了，把app删了，再重新来一遍还是这样显示  

1.app登录后ha里的移动应用里有你的手机吗？这样的话应该就是注册成功了，webhook id应该拿到了才对。直接反馈下不需要执行下面步骤；

2.如果移动应用里没有你的手机，先点击ha右下角用户头像，看下长期令牌里有没有产生。没有直接反馈

3.如果有新建一个长期令牌并复制值
尝试下下面请求：
[你的ha地址带端口号] 替换成你的ha地址
[长期令牌] 替换成你新建的长期令牌的复制的值，注意长期令牌和Bearer 间有一个空格
mac/linux终端运行：
```
curl --request POST \
  --url http://[你的ha地址带端口号]/api/mobile_app/registrations \
  --header 'Authorization: Bearer [长期令牌]' \
  --header 'content-type: application/json' \
  --data '{
      "device_id": "uuid",
      "app_id": "smart_house",
      "app_name": "Smart House",
      "app_version": "2.2.2",
      "device_name": "device_name",
      "manufacturer": "Android",
      "model": "xiaomi",
      "os_name": "",
      "os_version": "13",
      "supports_encryption": false,
      "app_data": {"push_websocket_channel": true}
    }'
```  
PC的cmd运行
```
curl --request POST ^
  --url http://[你的ha地址带端口号]/api/mobile_app/registrations ^
  --header "Authorization: Bearer  [长期令牌]" ^
  --header "content-type: application/json" ^
  --data "{\"device_id\": \"uuid\",\"app_id\": \"smart_house\",\"app_name\": \"Smart House\",\"app_version\": \"2.2.2\",\"device_name\": \"device_name\",\"manufacturer\": \"Android\",\"model\": \"xiaomi\",\"os_name\": \"\",\"os_version\": \"13\",\"supports_encryption\": false,\"app_data\": {\"push_websocket_channel\": true}}"
```  
pc运行结果: 
![image](https://github.com/nesror/SmartHouse/assets/8413360/3f58d78b-17d6-4b5e-9200-e0cc11232329)
看下有没有webhook_id

**Comment by nesror** [comment]
> > > 我的也是这样显示的，一开始还以为是非会员会这样显示，后面购买了vip还是这样显示，一脸懵逼。
> > 
> > 
> > app->设置->传感器设置->右上角重新注册 这样可以解决吗
> 
> 解决不了的，我把ha里的移动应用项目删了，把app删了，再重新来一遍还是这样显示

已经解决了，等待2.1.1版本的发布，预计下午2点前发布新版本
